/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenusRouteImport } from './routes/menus'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ChoiceRouteImport } from './routes/choice'
import { Route as IndexRouteImport } from './routes/index'

const MenusRoute = MenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoiceRoute = ChoiceRouteImport.update({
  id: '/choice',
  path: '/choice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choice': typeof ChoiceRoute
  '/experience': typeof ExperienceRoute
  '/menus': typeof MenusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choice': typeof ChoiceRoute
  '/experience': typeof ExperienceRoute
  '/menus': typeof MenusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/choice': typeof ChoiceRoute
  '/experience': typeof ExperienceRoute
  '/menus': typeof MenusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/choice' | '/experience' | '/menus'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/choice' | '/experience' | '/menus'
  id: '__root__' | '/' | '/choice' | '/experience' | '/menus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChoiceRoute: typeof ChoiceRoute
  ExperienceRoute: typeof ExperienceRoute
  MenusRoute: typeof MenusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menus': {
      id: '/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof MenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choice': {
      id: '/choice'
      path: '/choice'
      fullPath: '/choice'
      preLoaderRoute: typeof ChoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChoiceRoute: ChoiceRoute,
  ExperienceRoute: ExperienceRoute,
  MenusRoute: MenusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
