/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChoiceRouteImport } from './routes/choice'
import { Route as IndexRouteImport } from './routes/index'

const ChoiceRoute = ChoiceRouteImport.update({
  id: '/choice',
  path: '/choice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choice': typeof ChoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choice': typeof ChoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/choice': typeof ChoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/choice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/choice'
  id: '__root__' | '/' | '/choice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChoiceRoute: typeof ChoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/choice': {
      id: '/choice'
      path: '/choice'
      fullPath: '/choice'
      preLoaderRoute: typeof ChoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChoiceRoute: ChoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
